version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 315819558409.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t 315819558409.dkr.ecr.us-east-1.amazonaws.com/react-project:latest .
      - docker tag 315819558409.dkr.ecr.us-east-1.amazonaws.com/react-project:latest 315819558409.dkr.ecr.us-east-1.amazonaws.com/react-project:latest
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image..."
      - docker push 315819558409.dkr.ecr.us-east-1.amazonaws.com/react-project:latest

artifacts:
  files:
    - '**/*'
  base-directory: "./"
  name: react-project--artifact
  discard-paths: no
  s3-prefix: react-project/SourceArti/
