FROM node:latest

# Set working directory
WORKDIR /var/www/React_Project

# Copy application files
COPY . .

# Install dependencies and build React app
RUN npm install --force && npm run build

# Expose port 80
EXPOSE 80

# Start the React app
CMD ["npm", "start"]

